### ISSUE TITLE
Slack OOO Notification Bot

### ISSUE THREAD

**Issue by andela-anandaa** [LetsOpen/project-proposals#1]
### Description

A bot that helps everyone know whether someone is Out-of-Office (OOO). 

**User-flow:**
- When someone is going to be OOO, he tells the bot that he's going to be OOO
- They will have some little conversation with the bot e.g. _when will you come back from the OOO?_, _how can people reach you?_
### Team Members
- None (open project)
### Choice Technologies

Any (Python/NodeJS)
### Call for Collaboration

Need anyone that can take this up.

**Comment by goizueta** [comment]
Ran into this problem today after I ended up waiting for a response from several people that were on vacation.

**Comment by andela-anandaa** [comment]
Came across [Slack-OOO](https://github.com/shaunburdick/slack-ooo) today.

**Comment by goizueta** [comment]
Cool! Maybe we can still extend it a bit, looks like they have a few open issues.

**Comment by andela-anandaa** [comment]
Yes, I'm even in conversation with the author, he's open. I think we can pilot it at Andela and contribute back.

**Comment by andela-anandaa** [comment]
@goizueta -  I'm now contributing on [Slack-OOO](https://github.com/shaunburdick/slack-ooo) project. I'll be working on [one feature](https://github.com/shaunburdick/slack-ooo/issues/1) for persistence then we will deploy on Andela Slack org after discussing with Brice. cc. @Stephen-Njoroge

**Comment by Stephen-Njoroge** [comment]
great @andela-anandaa , that is great, how is the progress so far?

**Comment by andela-anandaa** [comment]
@Stephen-Njoroge Not done with the feature yet, hopefully this week.

**Comment by ghost** [comment]
@Stephen-Njoroge @Stephen-Njoroge @goizueta  Hi guys, this project is quite interesting. I've done some python and JS but I have no experience with Node-JS. However, I'm always looking to learn new things. Is there a way I can contribute to this project?

**Comment by andela-anandaa** [comment]
@AustinRoy7 - I'm working on some issues already, we can jam together if you want. Get my fork [here](https://github.com/andela-anandaa/slack-ooo). Let's talk on the Slack org, I'll start a channel for the project.

**Comment by Antoh1** [comment]
@andela-anandaa  this is great. As @AustinRoy7 , never used NodeJs too. Am only conversant with python and Angularjs. Looking forward for great stuff

**Comment by goizueta** [comment]
@andela-anandaa, you ended up getting your PR merged, right? Is there any other work to be done on this or can we close the issue?

**Comment by andela-anandaa** [comment]
@goizueta - That was a preliminary PR, was merged. But there is the major _issue_ on persisting data that I'm yet to finish on. However, we can have this closed and carry on the conversation on [our fork here](https://github.com/open-andela/slack-ooo).
